# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Roly < Formula
  desc "Set AWS environment variables based on your profile"
  homepage "https://github.com/diasjorge/roly/"
  version "0.1.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/diasjorge/roly/releases/download/v0.1.5/roly_0.1.5_darwin_amd64.tar.gz"
      sha256 "0e1dbd0b1d2fea69de14522812840b2e3261e55add3273e4b852ba0bff09445f"

      def install
        bin.install "roly"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/diasjorge/roly/releases/download/v0.1.5/roly_0.1.5_linux_amd64.tar.gz"
      sha256 "c720a2ec63670495df1444fa0f5973b9c558d2051727f542745c8770c3754343"

      def install
        bin.install "roly"
      end
    end
  end
end
